### Add offer
POST http://localhost:8080/libso/offers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "quantity" : 2,
  "endDate" : "2021-02-02",
  "product" :
  {
    "id": 1
  }
}

### Update offer
PUT http://localhost:8080/libso/offers/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id" : 1,
  "quantity" : 1,
  "endDate" : "2021-02-03",
  "creationDate" : "2020-12-09T18:29:15.743559000",
  "product" :
  {
    "id": 1
  }
}

### Find offer by category id
GET http://localhost:8080/libso/offers/categories/1
Authorization: Bearer {{auth_token}}

### Delete product
DELETE http://localhost:8080/libso/offers/1
Authorization: Bearer {{auth_token}}