### Add promotion
POST http://localhost:8080/libso/promotions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Letnia wyprzedaż",
  "percentValue" : 20,
  "startDate" : "2001-02-02T10:00:00",
  "endDate" : "2001-03-01T23:00:00"
}

### Update promotion
PUT http://localhost:8080/libso/promotions/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id" : 1,
  "name": "Jesienna wyprzedaż",
  "percentValue" : 40,
  "startDate" : "2001-03-02T15:00:00",
  "endDate" : "2001-04-02T00:00:00"
}

### Find all promotions
GET http://localhost:8080/libso/promotions
Authorization: Bearer {{auth_token}}

### Delete promotion
DELETE http://localhost:8080/libso/promotions/1
Authorization: Bearer {{auth_token}}