# FLYWAY TABLE
DROP TABLE FLYWAY_SCHEMA_HISTORY;

# JOIN TABLES
DROP TABLE TRANSACTION_PRODUCT;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE USER_AUTHORITY;

# ENTITY TABLES
DROP TABLE TRANSACTION;
DROP TABLE OFFER;
DROP TABLE PROMOTION;
DROP TABLE REVIEW;
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;
DROP TABLE AUTHORITY;
DROP TABLE ADDRESS;
DROP TABLE PERSON;
DROP TABLE TOKEN;
DROP TABLE USER;